# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c5dee011283e7e9eef079ed6e015c1f2"
name = "emailproof"
handle = "emailproof"
application_url = "https://respiratory-associate-res-nirvana.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-99fc8b06.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://respiratory-associate-res-nirvana.trycloudflare.com/auth/callback",
  "https://respiratory-associate-res-nirvana.trycloudflare.com/auth/shopify/callback",
  "https://respiratory-associate-res-nirvana.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
